# Numpy ndarray operations
## Reshaping arrays
Note:
- the size of the initial array must match the size of the reshaped array

In [8]:
# reshape a array of 1 through 9 in a 3X3 grid
import numpy as np

array1 = np.arange(start=1, stop=10, step=1)
print(array1)

grid = np.reshape(array1, shape=(3,3))
print(grid)
print("This is equivalent to")
# ndarray.reshape allows the shape parameters to be passed as separate arguments
grid1 = array1.reshape(3,3)
print(grid1)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
This is equivalent to
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Concatenation of arrays

In [9]:
import numpy as np

# concatenate one-dimensional array
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.concatenate([x, y])
print(z)

[1 2 3 3 2 1]


In [16]:
# concatenate two-dimensional array
grid2 = np.array([[1, 2, 3],
                  [4, 5, 6]])
grid3 = np.array([[7, 8, 9],
                  [10, 11, 12]])
grid4 = np.array([[13, 14, 15],])

grid_concatenate = np.concatenate([grid2, grid3, grid4])
print(grid_concatenate)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


## Computation on numpy arrays
### element-wise operations
Straightforward way to allow us to perform arithmetic operations on each element of the array directly.
Operators are equivalent to numpy nfuncs.
For example: `+` is equivalent to `np.add`, `-` is equivalent to `np.substract`


In [25]:
import numpy as np

x = np.array([1, 2, 3, 4])

print("****** basic arithmetic functions ******")
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

****** basic arithmetic functions ******
x      = [1 2 3 4]
x + 5  = [6 7 8 9]
x - 5  = [-4 -3 -2 -1]
x * 2  = [2 4 6 8]
x / 2  = [0.5 1.  1.5 2. ]
x // 2 = [0 1 1 2]
-x     =  [-1 -2 -3 -4]
x ** 2 =  [ 1  4  9 16]
x % 2  =  [1 0 1 0]


In [27]:
print("****** absolute values ******")
print("np.abs(x) =", np.abs(x))

print("\n****** Exponents and logarithms ******")
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

print("\nYou can also write more complex operations, like")
print("-(0.5*x + 1) ** 2 =", -(0.5*x + 1) ** 2)


****** absolute values ******
np.abs(x) = [1 2 3 4]

****** Exponents and logarithms ******
e^x = [ 2.71828183  7.3890561  20.08553692 54.59815003]
2^x = [ 2.  4.  8. 16.]
3^x = [ 3.  9. 27. 81.]
ln(x)    = [0.         0.69314718 1.09861229 1.38629436]
log2(x)  = [0.        1.        1.5849625 2.       ]
log10(x) = [0.         0.30103    0.47712125 0.60205999]
exp(x) - 1 = [ 1.71828183  6.3890561  19.08553692 53.59815003]
log(1 + x) = [0.69314718 1.09861229 1.38629436 1.60943791]

You can also write more complex operations, like
-(0.5*x + 1) ** 2 = [-2.25 -4.   -6.25 -9.  ]


### Matrix operations (dot product)

In [1]:
import numpy as np

matrix1 = np.array([[1, 2],
                    [3, 4]])
matrix2 = np.array([[5, 6],
                    [7, 8]])

print(f"The element-wise product of matrix1 and matrix2 is\n{matrix1 * matrix2}")
print(f"The dot product of matrix1 and matrix2 is\n{np.dot(matrix1, matrix2)}")


The element-wise product of matrix1 and matrix2 is
[[ 5 12]
 [21 32]]
The dot product of matrix1 and matrix2 is
[[19 22]
 [43 50]]


## Aggregations: min, max, and others

In [2]:
import numpy as np

x = np.array([1, 2, 3])
print(f"{x=}")
print(f"The minimum value of x is {x.min()}")
print(f"The maximum value of x is {x.max()}")
print(f"The average value of x is {x.mean()}")
print(f"The median value of x is {np.median(x)}") # note: ndarray does not have median attributed
print(f"The standard deviation of x is {x.std():.2f}")
print(f"The summation of x is {x.sum()}")


x=array([1, 2, 3])
The minimum value of x is 1
The maximum value of x is 3
The average value of x is 2.0
The median value of x is 2.0
The standard deviation of x is 0.82
The summation of x is 6


In [3]:
"multi-dimensional aggregation"

x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(f"The sum of all elements in x is {x.sum()}")
print(f"The sum of each column of x is {x.sum(axis=0)}")
print(f"The sum of each row of x is {x.sum(axis=1)}")

The sum of all elements in x is 45
The sum of each column of x is [12 15 18]
The sum of each row of x is [ 6 15 24]


In [62]:
"what if there are Nan values? There are NaN-safe versions of all those functions"

x = np.array([1, 2, 3, np.nan])

print(x.sum())
print(np.nansum(x))


nan
6.0
